version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $${MYSQL_PASSWORD}
      MYSQL_DATABASE: $${MYSQL_DB}
      MYSQL_USER: $${MYSQL_USER}
      MYSQL_PASSWORD: $${MYSQL_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql/

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery_worker:
    image: app-image
    command:
      - run_celery
    environment:
      - BROKER_URL=redis://redis:6379/
      - C_FORCE_ROOT=true
    volumes:
      - ./:/app/
    depends_on:
      - redis
      -  mysql_db

  app:
    image: app-image
    build: .
    command:
      - run_dev
    env_file:
      - .env
    tty: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      -  mysql_db
      -  redis
