# Generated by Django 4.2.7 on 2023-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('pub_year', models.IntegerField(verbose_name='Год публикации')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
    ]
